# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3dc42d461f15b1ce3dbacf73e12b3350c7a1062615238a99e79e49bc62512b5f4c7aaf79e01bf9764196d8ab14a8fc3774a1b9ef379aed1ddde26b8c5be6490

test:
  secret_key_base: 2c08b2908e236d2b80c6feaf02bdfc9b24ec26f5b9ce0d2c3596dde8aa4efbc0ae25d70571a2a55821c5a03301ff324e3f327df98b7739916763c0dd15b96096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
